#!/usr/bin/env bash

set -euo pipefail

#t=/tmp/foo
#rm -rf /tmp/foo
#mkdir /tmp/foo
t="$(mktemp -d)"

export GIT_DIR="$t/.git"
export GIT_WORK_TREE="$t"
git init --quiet

echo export GIT_DIR="$t/.git"
echo export GIT_WORK_TREE="$t"

short_filename() {
  basename $1 .yml \
  | cut -c1-${2:-999}
}

input_manifest="$1"
shift
manifest_filename="$(basename $input_manifest)"
output_manifest="$t/$manifest_filename"

bosh interpolate "$input_manifest" >"$output_manifest"

git add -- "$manifest_filename" >/dev/null
git commit -m "$(short_filename $manifest_filename)" >/dev/null

ops_args=""

for ops_file; do
  ops_args+=" -o $ops_file"
  bosh interpolate "$input_manifest" $ops_args >"$output_manifest" \
  || { echo "Failed to apply ops file '$ops_file'; bailing out ..." >&2; false; }
  git commit -m "$(short_filename ${ops_file})" -- "$output_manifest" >/dev/null \
  || true
done 

